
name: update_readme

on:
  workflow_dispatch:
  schedule:
    - cron: "*/30 * * * *"   # every 30 mins

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Obtain GitHub App Installation Access Token
        id: githubAppAuth
        run: |
         TOKEN="$(npx obtain-github-app-installation-access-token ci ${{ secrets.SNAPI_APP_CREDENTIALS_TOKEN }})"
         echo "::add-mask::$TOKEN"
         echo "token=$TOKEN" >> $GITHUB_OUTPUT
      - name: üçΩÔ∏è Get working copy
        uses: actions/checkout@master
        with:
          fetch-depth: 1                                                                 
      - name: üêç Set up Python 3.8                               
        uses: actions/setup-python@v2                               
        with:                                 
          python-version: '3.8'                                                   
      - name: üíø Install Jinja2 & requests                           
        run: pip install Jinja2 requests
      - name: üç≥ Update README
        run: |
          cd ${GITHUB_WORKSPACE}/.github/profile/src/
          python update.py
      - name: üöÄ Deploy
        run: |
          git config user.name "SNAPI Github Actions"
          git config user.email "SNAPI-Github-Actions@users.noreply.github.com"
          git add .
          git commit -am "feat(auto generate): Updated README"
          git push --all -f https://${{ steps.githubAppAuth.outputs.token }}@github.com/${GITHUB_REPOSITORY}.git
t
